event_left_topic : '/prophesee/camera_left/cd_events_buffer_reconstructed'
event_right_topic : '/prophesee/camera_right/cd_events_buffer_reconstructed'
rgb_left_topic : '/stereo/left/image_mono'
rgb_right_topic : '/stereo/right/image_mono'
imu_topic : '/imu/data'
# kinect_depth_topic : '/depth/image_raw'
# kinect_rgb_topic : '/rgb/image_raw'
# lidar_topic : '/os_cloud_node/points'

out_event_left_topic : '/prophesee/left/cd_events_buffer'
out_event_right_topic : '/prophesee/right/cd_events_buffer'
out_rgb_left_topic : '/stereo/left/image_mono'
out_rgb_right_topic : '/stereo/right/image_mono'
out_imu_topic : '/imu/data'
# out_kinect_depth_topic : '/kinect/depth_image'
# out_kinect_rgb_topic : '/kinect/depth_image'
# out_lidar_topic : '/os/point_cloud'


rawbag_path : '/home/yuxuan/Downloads/joint_calibration1.bag'
output_path : '/home/yuxuan/Downloads/joint_calibration1_recons.bag'

gt_path : '/home/yuxuan/Downloads/joint_calibration1.csv'
out_gt_topic : '/opti/pose'